files:
  includes:
    - '\.yaml$'
  excludes:
    - '\.generated\.yaml$'
    - '\/system\/.*\.yaml$'
registries:
  my-docker-registry:
    type: docker
    interval: 1h
    url: https://registry-1.docker.io
  my-helm-registry:
    type: helm
    interval: 1h
    url: https://helm.nginx.com/stable
  my-git-hub-tag-registry:
    type: git-hub-tag
    interval: 1h
policies:
  my-semver-policy:
    pattern: '^v?(?P<version>.*)$'
    extracts:
      - type: semver
        value: '<version>'
        pinMajor: true
        pinMinor: true
