apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
fail: fail # git-ops-update {"will":"fail2"}
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: 0.10.1 # git-ops-update {"registry":"my-helm-registry","resource":"nginx-ingress","policy":"my-semver-policy","action":"push"}
