namespace: ingress-nginx
bases:
  - github.com/kubernetes/ingress-nginx/deploy/static/provider/kind?ref=controller-v1.0.0 # git-ops-update {"registry":"my-git-hub-tag-registry","resource":"kubernetes/ingress-nginx","policy":"my-semver-policy","action":"push","prefix":"controller-","format":"regexp:ref=(?P<version>.*)$"}
