definitions:
  creds: &creds
    username: user
    password: pass
files:
  includes:
  - '\.yaml$'
  excludes:
  - '\.generated\.yaml$'
registries:
  docker:
    type: docker
    interval: 1m
    url: https://registry-1.docker.io
    credentials: *creds
  helm:
    type: helm
    interval: 1h
    url: https://charts.helm.sh/stable
    credentials: *creds
  git-hub:
    type: git-hub-tag
    interval: 1h
    url: https://api.github-enterprise.com
    credentials: *creds
policies:
  lexicographic:
    pattern: '^(?P<all>.*)$'
    extracts:
    - type: lexicographic
      value: '<all>'
      pin: true
  numeric:
    pattern: '^(?P<all>.*)$'
    extracts:
    - type: numeric
      value: '<all>'
      pin: true
  semver:
    pattern: '^(?P<all>.*)$'
    extracts:
    - type: semver
      value: '<all>'
      pinMajor: true
      pinMinor: true
      pinPatch: true
      allowPrereleases: true
git:
  author:
    name: name
    email: email
  gitHub:
    accessToken: access_token
